---
version: "2.0"
services:
  app:
    image: cro7/narratai:0.0.1
    expose:
      - port: 7860
        as: 80
        to:
          - global: true

profiles:
  compute:
    app:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - size: 30Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                 - model: rtx4090
                 - model: rtx3090
                 - model: v100
                 - model: p100
                 - model: p40

  placement:
    dcloud:
      pricing:
        app:
          denom: uakt
          amount: 1000
deployment:
  app:
    dcloud:
      profile: app
      count: 1